# Train semanric model

## Prepare title list

In [1]:
import os
import pandas as pd
import sys

from pathlib import Path
current_dir = Path.cwd().resolve()
project_root = str(current_dir.parent if current_dir.name == "notebooks" else current_dir)

if project_root not in sys.path:
    sys.path.insert(0, project_root)

## Training model

In [2]:
from src.semantic.SemanticTraining import SentenceVector
from src.core.Models import Models
from src.core.Context import context

In [3]:
title_list = context.title_list

In [4]:
model = Models()

sentence_vector = SentenceVector(model.sentence_model)

semantic_vector_list = sentence_vector.get_vector(
    title_list
)
# print(model_context.semantic_vector_list)
sentence_vector.overview()

metric, example = sentence_vector.summary()

print("\nSummary of Sentence Embedding:")
display(metric)
print("\nExample of Sentence Embedding:")
display(example)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/1603 [00:00<?, ?it/s]

============================================================
Sentence Embedding Overview
[Sentence is: N55528]
============================================================
Documents : 51282
Dimension : 384
Shape     : (384,)

First vector (first 10 values):
[-0.0092864   0.04244237  0.05898825  0.01210566  0.03341921  0.01964547
  0.02736868 -0.06152722 -0.03616752 -0.03904743] ...

Summary of Sentence Embedding:

                Metric                Value
0      Embedding Model  SentenceTransformer
1  Number of Documents                51282
2  Embedding Dimension                  384
3         Output Shape               (384,)

Example of Sentence Embedding:

,News ID,Sample Title,Embedding (first 10 dims)
0,N55528,"The Brands Queen Elizabeth, Prince Charles, an...","[-0.0093, 0.0424, 0.0590, 0.0121, 0.0334, 0.01..."

In [5]:
vector_df = pd.DataFrame({
    "News_ID": semantic_vector_list.keys(),
    "semantic_vector": semantic_vector_list.values()
})

vectors_dir = os.path.join(project_root, "vectors")
os.makedirs(vectors_dir, exist_ok=True)
vector_df.to_pickle(os.path.join(vectors_dir, "semantic_vectors.pkl"))