Import primary library

In [132]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from IPython.display import display
import json

np.set_printoptions(
    precision=4,      # 4 chữ số thập phân
    suppress=True,    # không dùng dạng 1.23e-05
    linewidth=200     # tránh xuống dòng quá sớm
)

In [133]:
import os
import kagglehub
import shutil
from sklearn.feature_extraction.text import CountVectorizer

Load Data

In [134]:
path = kagglehub.dataset_download(
    "arashnic/mind-news-dataset"
)

print("Dataset downloaded to: ", path)

Dataset downloaded to:  C:\Users\tonmi\.cache\kagglehub\datasets\arashnic\mind-news-dataset\versions\2

Copy data to working dir

In [135]:
source = os.path.join(path, "MINDsmall_train")

destination = r"D:\CDNC\MIND-research\data\raw"

os.makedirs(destination, exist_ok=True)

files = [
    "news.tsv",
    "behaviors.tsv",
    "entity_embedding.vec",
    "relation_embedding.vec",
]

for file in files:
    shutil.copy2(
        os.path.join(source, file),
        os.path.join(destination, file)
    )

print("Done")

Done

Get split-dataset - 300 line - News_ID + Category + News title

In [136]:
news_path = os.path.join(destination, "news.tsv")

if not os.path.exists(news_path):
    f_news_small = open(news_path, "x", encoding="utf-8")


columns = [
    "News_ID",
    "Category",
    "SubCategory",
    "Title",
    "Abstract",
    "URL",
    "Title_Entities",
    "Abstract_Entities"
]

news = pd.read_csv(
    news_path,
    sep="\t",
    names=columns,
    
)

news = news[["News_ID", "Category", "Title"]]

sample = news.sample(
    n=300,
    random_state=42
).reset_index(drop=True)

sample = news.head(300)
sample_dir = r"D:\CDNC\MIND-research\data\sample"

sample.to_csv(
    os.path.join(sample_dir, "news.csv"),
    index=False
)

print(sample.head())
print("Sample shape: ", sample.shape)

  News_ID   Category                                              Title
0  N55528  lifestyle  The Brands Queen Elizabeth, Prince Charles, an...
1  N19639     health                      50 Worst Habits For Belly Fat
2  N61837       news  The Cost of Trump's Aid Freeze in the Trenches...
3  N53526     health  I Was An NBA Wife. Here's How It Affected My M...
4  N38324     health  How to Get Rid of Skin Tags, According to a De...
Sample shape:  (300, 3)

In [137]:
from sentence_transformers import SentenceTransformer
from bertopic import BERTopic

class Models:
    def __init__(self):
        self.sentence_model = SentenceTransformer("all-MiniLM-L6-v2")

        self.svectorizer = CountVectorizer(
                stop_words="english",
            )

        self.topic_model = BERTopic(
            calculate_probabilities=True, # Important to set this to True for probability calculations
            verbose=True,
            vectorizer_model=self.svectorizer
        )

models = Models()

class VectorContext:
    def __init__(self):
        self.title_list = None
        self.semantic_vector_list = None
        self.probabilities_list = None
        self.topics_vector_list = None

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

### Vector Factory

`VectorFactory` được sử dụng để tạo đối tượng biểu diễn vector tương ứng với từng mô hình thông qua một giao diện thống nhất. Thay vì khởi tạo trực tiếp từng lớp, người dùng chỉ cần chỉ định loại mô hình (`sentence` hoặc `bertopic`), Factory sẽ trả về đối tượng phù hợp.

Thiết kế này giúp:
- Tách biệt logic khởi tạo khỏi logic xử lý.
- Dễ dàng thay thế hoặc mở rộng sang các mô hình mới mà không ảnh hưởng đến mã nguồn hiện có.
- Tăng khả năng bảo trì và tái sử dụng mã nguồn.

Vector Interface

In [138]:
from abc import ABC, abstractmethod

class Vector(ABC):
    @abstractmethod
    def get_vector(self):
        pass
    
    @abstractmethod
    def overview(self):
        pass

    @abstractmethod
    def summary(self):
        pass

Semantic vector

In [139]:
class SentenceVector(Vector):
    def __init__(self, model):
        self.model = model
        self.semantic_vector = None

    def get_vector(self, title_list):
        self.title_list = title_list
        
        titles = [news["title"] for news in title_list]

        vectors = self.model.encode(
            titles,
            show_progress_bar=True,
            convert_to_numpy=True
        )
        
        self.semantic_vector = {
            news["news_id"]: vector for news, vector in zip(title_list, vectors)
        }
        return self.semantic_vector
    
    def overview(self):
        print("=" * 60)
        print("Sentence Embedding Overview")
        print(f"[Sentence is: {list(self.semantic_vector.keys())[0]}]")
        print("=" * 60)

        print(f"Documents : {len(self.semantic_vector)}")
        print(f"Dimension : {self.semantic_vector[list(self.semantic_vector.keys())[0]].shape[0]}")
        print(f"Shape     : {self.semantic_vector[list(self.semantic_vector.keys())[0]].shape}")

        print("\nFirst vector (first 10 values):")
        print(self.semantic_vector[list(self.semantic_vector.keys())[0]][:10], "...")

    def summary(self, sample_index=0):

        sample = self.title_list[sample_index]

        news_id = sample["news_id"]
        title = sample["title"]

        vector = self.semantic_vector[news_id]

        metrics = pd.DataFrame({
            "Metric": [
                "Embedding Model",
                "Number of Documents",
                "Embedding Dimension",
                "Output Shape"
            ],
            "Value": [
                self.model.__class__.__name__,
                len(self.semantic_vector),
                vector.shape[0],
                str(vector.shape)
            ]
        })

        vector_preview = ", ".join(
            f"{x:.4f}" for x in vector[:10]
        ) + ", ..."

        example = pd.DataFrame({
            "News ID": [news_id],
            "Sample Title": [title],
            "Embedding (first 10 dims)": [
                f"[{vector_preview}]"
            ]
        })

        return metrics, example

Topic vector

In [140]:
class BERTopicVector(Vector):
    def __init__(self, model):
        self.model = model

        self.notice = "BERTopic depends on the sentence transformer model." \
        " Please ensure that the sentence transformer model is trained before using BERTopic."

        self.probabilities = None
        self.topics_vector = None

    def get_vector(self, title_list, semantic_vector=None):
        self.title_list = title_list
        
        titles = [news["title"] for news in title_list]

        embeddings = np.array([
            semantic_vector[news["news_id"]]
            for news in title_list
        ])
        
        if semantic_vector is None:
            print(self.notice)
            return
        
        topics, probabilities = self.model.fit_transform(
                                    titles,
                                    embeddings,
                                )
        
        self.topic_vector = {
            news["news_id"]: {
                "topic": topic,
                "probability": probability
            }
            for news, topic, probability in zip(
                title_list,
                topics,
                probabilities
            )
        }

        return self.topic_vector
    
    def overview(self):

        print("=" * 60)
        print("BERTopic Overview")
        print("=" * 60)

        print(f"Number of documents : {len(self.title_list)}")
        print(f"Number of topics    : {len(set(v['topic'] for v in self.topic_vector.values()) - {-1})}")

        print("\nTopic distribution:")
        print(self.model.get_topic_info()[["Topic", "Count"]])

        print("\nFirst 5 documents:")

        for sample in self.title_list[:5]:

            news_id = sample["news_id"]
            title = sample["title"]

            topic = self.topic_vector[news_id]["topic"]

            print(f"{news_id}")
            print(f"Title : {title}")
            print(f"Topic : {topic}")
            print("-" * 40)

        first_probability = next(iter(self.topic_vector.values()))["probability"]

        print("\nProbability shape:")
        print(first_probability.shape)

        print("\nFirst 5 probability vectors:")

        for sample in self.title_list[:5]:

            news_id = sample["news_id"]

            probability = self.topic_vector[news_id]["probability"]

            preview = ", ".join(
                f"{p:.4f}" for p in probability[:10]
            )

            print(f"{news_id} -> [{preview}, ...]")

    
    def summary(self, sample_index=0):

        # =========================
        # Metrics
        # =========================

        topics = [
            value["topic"]
            for value in self.topic_vector.values()
        ]

        first_probability = next(iter(self.topic_vector.values()))["probability"]

        metrics_df = pd.DataFrame({
            "Metric": [
                "Topic Model",
                "Number of Documents",
                "Number of Topics",
                "Number of Outliers",
                "Probability Shape"
            ],
            "Value": [
                self.model.__class__.__name__,
                len(self.title_list),
                len(set(topics) - {-1}),
                np.sum(np.array(topics) == -1),
                str(first_probability.shape)
            ]
        })

        # =========================
        # Topic Information
        # =========================

        topic_df = self.model.get_topic_info()[["Topic", "Count"]].copy()

        keywords = []

        for topic in topic_df["Topic"]:

            if topic == -1:
                keywords.append("Outlier")
            else:
                words = [
                    word
                    for word, _ in self.model.get_topic(topic)[:5]
                ]
                keywords.append(", ".join(words))

        topic_df["Top Keywords"] = keywords

        # =========================
        # Sample
        # =========================

        sample = self.title_list[sample_index]

        news_id = sample["news_id"]
        title = sample["title"]

        topic_info = self.topic_vector[news_id]

        probs = ", ".join(
            f"{p:.4f}"
            for p in topic_info["probability"]
        )

        sample_df = pd.DataFrame({
            "News ID": [news_id],
            "Sample Title": [title],
            "Assigned Topic": [
                topic_info["topic"]
            ],
            "Probability Distribution": [
                f"[{probs}]"
            ]
        })

        return metrics_df, topic_df, sample_df

Title list

In [141]:
model_context = VectorContext()
to_dict = lambda news: {"news_id": news["News_ID"], "title": news["Title"]}
model_context.title_list = [to_dict(news) for _, news in sample.iterrows()]

print(model_context.title_list)

[{'news_id': 'N55528', 'title': 'The Brands Queen Elizabeth, Prince Charles, and Prince Philip Swear By'}, {'news_id': 'N19639', 'title': '50 Worst Habits For Belly Fat'}, {'news_id': 'N61837', 'title': "The Cost of Trump's Aid Freeze in the Trenches of Ukraine's War"}, {'news_id': 'N53526', 'title': "I Was An NBA Wife. Here's How It Affected My Mental Health."}, {'news_id': 'N38324', 'title': 'How to Get Rid of Skin Tags, According to a Dermatologist'}, {'news_id': 'N2073', 'title': 'Should NFL be able to fine players for criticizing officiating?'}, {'news_id': 'N49186', 'title': "It's been Orlando's hottest October ever so far, but cooler temperatures on the way"}, {'news_id': 'N59295', 'title': 'Chile: Three die in supermarket fire amid protests'}, {'news_id': 'N24510', 'title': 'Best PS5 games: top PlayStation 5 titles to look forward to'}, {'news_id': 'N39237', 'title': 'How to report weather-related closings, delays'}, {'news_id': 'N9721', 'title': '50 Foods You Should Never Eat, According to Health Experts'}, {'news_id': 'N60905', 'title': 'Trying to Make a Ram 3500 as Quick as a Viper Requires Some Disassembly'}, {'news_id': 'N39758', 'title': '25 Biggest Grocery Store Mistakes Making You Gain Weight'}, {'news_id': 'N28361', 'title': 'Instagram Filters with Plastic Surgery-Inspired Effects Could Soon Disappear'}, {'news_id': 'N18680', 'title': 'Michigan apple recall: Nearly 2,300 crates could be contaminated with listeria'}, {'news_id': 'N55610', 'title': "Kate Middleton's Best Hairstyles Through the Years"}, {'news_id': 'N35621', 'title': 'Stars who got fired from major projects'}, {'news_id': 'N22850', 'title': "Newark Liberty Airport's Terminal One a $2.7 billion 'transformative' project"}, {'news_id': 'N58173', 'title': 'Is This The 2021 GMC Yukon Denali?'}, {'news_id': 'N29120', 'title': 'John Dorsey admits talks with Washington, but it "takes two to tango"'}, {'news_id': 'N9786', 'title': 'Elijah Cummings to lie in state at US Capitol Thursday'}, {'news_id': 'N47705', 'title': '17 Abandoned Theme Parks to Explore for Thrills, Chills, and Nostalgia'}, {'news_id': 'N3574', 'title': 'Ford Bronco Test Mule Spotted Flexing Its Muscles in Australia'}, {'news_id': 'N42474', 'title': "Trump's Trustbusters Bring Microsoft Lessons to Big Tech Fight"}, {'news_id': 'N64498', 'title': 'PGA Tour winners'}, {'news_id': 'N7517', 'title': '10 Things You Never Knew About Owls'}, {'news_id': 'N63665', 'title': '25 Last-Minute Ideas That Will Absolutely Save Your Holiday Dinner'}, {'news_id': 'N59469', 'title': 'Every outfit Duchess Kate has worn in 2019'}, {'news_id': 'N57356', 'title': 'New iPad Pro 2019 release date, price, news and leaks'}, {'news_id': 'N15926', 'title': 'These Simple Diet Changes Helped This Guy Lose 75 Pounds in 9 Months'}, {'news_id': 'N43620', 'title': 'Without help from US, UN climate fund struggles to meet goal'}, {'news_id': 'N60603', 'title': 'Best PS4 games 2019: play great PlayStation 4 games'}, {'news_id': 'N40078', 'title': 'The 23 Best TV Reboots of All Time'}, {'news_id': 'N61409', 'title': 'Netflix hackers: Why they steal passwords'}, {'news_id': 'N46013', 'title': '20 Must-Try Gravy Recipes for Your Thanksgiving Feast'}, {'news_id': 'N50643', 'title': 'A little snow causes a big mess, more than 100 crashes on Minnesota roads'}, {'news_id': 'N60723', 'title': 'Extinction Rebellion wins court challenge against London police'}, {'news_id': 'N63175', 'title': 'LA rivalry takes on new meaning for fans as Lakers, Clippers in hunt for NBA championship'}, {'news_id': 'N22028', 'title': 'Mom with schizophrenia, 6-year-old daughter missing in Queens'}, {'news_id': 'N8795', 'title': "5 Things You Probably Shouldn't Be Buying from Costco"}, {'news_id': 'N43647', 'title': "POWER RANKING: Here's who has the best chance of becoming the 2020 Democratic presidential nominee"}, {'news_id': 'N41835', 'title': 'Today in History: November 2'}, {'news_id': 'N8071', 'title': "25 Photos of the Royal Family at Balmoral Castle, Queen Elizabeth's Favorite Home"}, {'news_id': 'N26926', 'title': "I'm Afraid to Tell My Male Bosses I'm Pregnant"}, {'news_id': 'N49265', 'title': 'These Cranberry Sauce Recipes Are Perfect for Thanksgiving Dinner'}, {'news_id': 'N5124', 'title': 'Phil Fulmer blasts NCAA after key Tennessee freshman denied eligibility'}, {'news_id': 'N42777', 'title': "Prince George's Royal Life in Photos"}, {'news_id': 'N41387', 'title': 'Can you answer these real Jeopardy questions about TV shows?'}, {'news_id': 'N41106', 'title': "Randall's Rant: Is Tiger already the GOAT without 18 majors?"}, {'news_id': 'N37243', 'title': 'The 25 most desirable places to live in the US in 2019'}, {'news_id': 'N20139', 'title': "40+ Stuffed Pasta Recipes You'll Want To Make Every Night"}, {'news_id': 'N9680', 'title': "'Bachelor's Amanda Stanton Is Dating 'Rich Kids of Beverly Hills' Star Brendan Fitzpatrick"}, {'news_id': 'N35518', 'title': "I'm Sorry, But Please Do Not Put Your Purse On My Couch"}, {'news_id': 'N60434', 'title': "It's Not All About the Corgis - Here Are the Royal Family's Other Beloved Pets"}, {'news_id': 'N48239', 'title': '2020 Toyota Supra GT4 details announced, makes 429 horsepower'}, {'news_id': 'N40045', 'title': "Tim Burton's Original Art Is on Display at the Neon Museum in Las Vegas"}, {'news_id': 'N43946', 'title': "16 Live-Action Disney Movies in the Works After 'Maleficent: Mistress of Evil' (Photos)"}, {'news_id': 'N10836', 'title': '100 Genius Tips that Will Make Your Holidays So Much Better'}, {'news_id': 'N49585', 'title': "What's new in Germany and the Low Countries for 2019"}, {'news_id': 'N24798', 'title': 'Millennials are killing purse sales and replacing them with backpacks'}, {'news_id': 'N64668', 'title': "23 Things Car Dealerships Don't Want You To Know"}, {'news_id': 'N27435', 'title': 'Locked On Suns Wednesday: Suns blast Kings to begin 2019-20 season'}, {'news_id': 'N3395', 'title': "TV shows we're most excited about for the rest of the year"}, {'news_id': 'N53133', 'title': 'The Absolute Best One-piece Bathing Suits of 2019'}, {'news_id': 'N30702', 'title': '40 Things I Wish I Could Tell My Younger Self'}, {'news_id': 'N14538', 'title': 'Why Is This Weird Chevy Colorado Test Mule Trolling Ford HQ?'}, {'news_id': 'N37188', 'title': '20 Words and Phrases You Had No Idea Were Coined in New York City'}, {'news_id': 'N1032', 'title': "All of Kevin Harvick's Monster Energy Series victories"}, {'news_id': 'N30953', 'title': 'PCC Community Markets Plans Its First Fast Casual Restaurant Inside New Ballard Store'}, {'news_id': 'N10886', 'title': 'Where to Find a Good, Cheap Sandwich in Every State'}, {'news_id': 'N52386', 'title': '16 major chains where you can buy plant-based versions of your fast-food favorites'}, {'news_id': 'N22218', 'title': 'Do You Hate Meditating? So Do These People, But They Do It Anyway'}, {'news_id': 'N57388', 'title': "So far the World Series is one big reminder that you can't predict October baseball"}, {'news_id': 'N30389', 'title': '40 Celebrity Mothers and Daughters at the Same Age'}, {'news_id': 'N16104', 'title': 'The Top 50 Fast Food Restaurants in America'}, {'news_id': 'N25540', 'title': 'Take heart, millennials: Investing is within your reach'}, {'news_id': 'N51343', 'title': 'Viral college football fan under fire for past offensive tweets'}, {'news_id': 'N60774', 'title': "Watch this priest perform a 'spirited' dance at pep rally"}, {'news_id': 'N37129', 'title': "Don't Be Like These Celebrities Convicted of Tax Evasion"}, {'news_id': 'N64723', 'title': 'All eyes on Drew Brees as possibility of return nears'}, {'news_id': 'N3080', 'title': 'Restaurants to Satisfy Late Night Cravings in Louisville and Beyond'}, {'news_id': 'N40494', 'title': 'Cutest photos of the royal Cambridge kids'}, {'news_id': 'N15839', 'title': "2021 Cadillac Escalade's Interior Spied for Real"}, {'news_id': 'N19163', 'title': "Veneno Roadster, One:1, One-77, LaFerrari, P1, Veyron headline 25-car Bonham's auction"}, {'news_id': 'N13343', 'title': "46 Mismatched Nail Ideas You'll Want to Copy Immediately"}, {'news_id': 'N60852', 'title': 'In Photos: Flooding across the globe'}, {'news_id': 'N61864', 'title': 'The News In Cartoons'}, {'news_id': 'N36064', 'title': 'More store closings coming: The list of retailers closing locations in 2019'}, {'news_id': 'N35788', 'title': 'Extreme Jeep Wrangler Prototype Caught Testing in Michigan'}, {'news_id': 'N61167', 'title': 'Must-see biopics'}, {'news_id': 'N27190', 'title': 'Redskins place TE Jordan Reed on injured reserve, ending his season'}, {'news_id': 'N9035', 'title': 'NFL Week 9 Odds: Point Spreads, Betting Lines For All 14 Football Games'}, {'news_id': 'N19651', 'title': '27 products you only need to buy once in your life'}, {'news_id': 'N22957', 'title': 'Ranking 26 fast-food fried-chicken sandwiches (including Popeyes)'}, {'news_id': 'N63006', 'title': '17 Surprising Ways Penny-Pinching Costs You More'}, {'news_id': 'N5159', 'title': "The Fascinating Story Behind Where 'Hocus Pocus' Was Filmed"}, {'news_id': 'N47685', 'title': 'Early symptoms of dementia: Be aware of subtle signs'}, {'news_id': 'N44720', 'title': 'Man killed in officer-involved shooting in St. Louis'}, {'news_id': 'N55024', 'title': '40 Etiquette Mistakes You Need to Stop Making by Age 40'}, {'news_id': 'N44162', 'title': 'Patriots vs. Ravens: 3 keys to the game, fun facts, prediction'}, {'news_id': 'N52683', 'title': '14 Celebs Over 50 Who Are In The Best Shape Of Their Lives'}, {'news_id': 'N8185', 'title': 'The Oldsmobile Toronado - was it the ultimate personal car?'}, {'news_id': 'N1358', 'title': "With impeachment inquiry 'concerns' getting addressed, GOP have nowhere to go"}, {'news_id': 'N39817', 'title': '28 Surprisingly Good Costco, Walmart, and Target Products'}, {'news_id': 'N54799', 'title': "17 Low-Impact Workouts You Should Try If You're Not In Your 20s Anymore"}, {'news_id': 'N34169', 'title': 'When royals lose their tempers, from the Queen to Kate Middleton'}, {'news_id': 'N33303', 'title': '25 Hot Jobs That Pay More Than $100,000 a Year'}, {'news_id': 'N51340', 'title': "Queen Elizabeth's Cousin Says Royal Family 'Don't Communicate Very Well'"}, {'news_id': 'N46021', 'title': '12 ways your skin can react to stress, according to a dermatologist'}, {'news_id': 'N13855', 'title': 'Ikea US president backpedals on meeting parents of children killed by recalled dressers'}, {'news_id': 'N16556', 'title': 'Multi-vehicle accident on I-64 in James City County causes miles-long backup'}, {'news_id': 'N22679', 'title': 'Dissecting the softer, gentler Tiger Woods'}, {'news_id': 'N24423', 'title': '39 Appetizers for a Crowd That Are Easy and Unexpected'}, {'news_id': 'N20084', 'title': "How To Guess Someone's Zodiac Sign"}, {'news_id': 'N18393', 'title': 'What Men Find Attractive According To Their Zodiac Sign'}, {'news_id': 'N7141', 'title': 'Rams Week 8 snap count analysis'}, {'news_id': 'N11663', 'title': 'These College Friends Pledged To Stay In Touch---60 Years Later, They Still Do'}, {'news_id': 'N55435', 'title': 'Photos of College Football Cheerleaders'}, {'news_id': 'N39173', 'title': '5 reasons Gen Xers are struggling with retirement savings'}, {'news_id': 'N33874', 'title': 'The Most Important Things Fatherhood Has Taught Me About Being a Man'}, {'news_id': 'N44661', 'title': 'Fall Home Maintenance Checklist: 20 Things to Do Every Year'}, {'news_id': 'N41976', 'title': 'Study: Third-Hand Smoke Can Damage Your Lungs'}, {'news_id': 'N36820', 'title': 'Toad, Pasta and Other Unusual Names for Money Around the World'}, {'news_id': 'N54727', 'title': 'The surprising age differences between your favorite royal couples'}, {'news_id': 'N11683', 'title': 'BP profit beats as strong refining offsets lower oil price'}, {'news_id': 'N19401', 'title': 'Best website defacement monitoring service of 2019'}, {'news_id': 'N31442', 'title': 'How to Take Chicken Breasts From Frozen to Shredded in an Instant'}, {'news_id': 'N47214', 'title': 'Here are the lawmakers who are not seeking reelection to Congress in 2020'}, {'news_id': 'N31402', 'title': 'The Best Seafood Restaurant in All 50 States'}, {'news_id': 'N61358', 'title': '5 Foods That Can Actually Help Prevent Gray Hair'}, {'news_id': 'N48632', 'title': 'How much you must earn to be in the top 10% in your state'}, {'news_id': 'N57699', 'title': 'Ahad Israfil, gunshot wound survivor, dies'}, {'news_id': 'N27214', 'title': '19 Super Delicious Fall Soups Made From Scratch to Try Now (Including Pumpkin!)'}, {'news_id': 'N25174', 'title': 'Winter Storm Warning For Metro Denver, Boulder: Update'}, {'news_id': 'N51426', 'title': "Kanye West's 'Jesus is King' album still isn't here, fans aren't happy"}, {'news_id': 'N41013', 'title': "Doug Schoen: Hillary vs. Trump in 2020? If Clinton is serious, here's best way for her to defeat the president"}, {'news_id': 'N19888', 'title': 'Titans force 4 turnovers by Winston, hold off Buccaneers'}, {'news_id': 'N45191', 'title': 'Amazon Says These Are Its Funniest Customer Reviews'}, {'news_id': 'N60535', 'title': 'Josh Gordon, New Patriots Receiver Mohamed Sanu Share Laugh At Practice'}, {'news_id': 'N47600', 'title': "People Told My Daughter With a Disability She Wouldn't Be Able to Do Everything She Does Today"}, {'news_id': 'N35318', 'title': "It's illegal to leave your pumpkins outside in Maricopa County"}, {'news_id': 'N11360', 'title': 'This is how much water you need to drink for weight loss'}, {'news_id': 'N13566', 'title': '30 Least Expensive Dog Breeds'}, {'news_id': 'N24417', 'title': 'Cavs could put claim on Alfonzo McKinnie after surprising release from Warriors'}, {'news_id': 'N59891', 'title': 'Maryland police ID man killed in crash of semi hauling beer'}, {'news_id': 'N30236', 'title': 'American teenager Gauff reaches maiden WTA final in Linz'}, {'news_id': 'N64593', 'title': "An avocado a day could lower your 'bad' cholesterol levels and reduce your risk of heart disease"}, {'news_id': 'N45970', 'title': "The Latest: House measure condemns Trump's Syria withdrawal"}, {'news_id': 'N54542', 'title': 'Police searching for thief stealing cars at Atlanta airport'}, {'news_id': 'N30290', 'title': "The Real Reason McDonald's Keeps the Filet-O-Fish on Their Menu"}, {'news_id': 'N51844', 'title': '29 Thanksgiving Menus That Will Make November So Much Easier'}, {'news_id': 'N7992', 'title': 'You can now stay in a giant guitar-shaped hotel that you have to see to believe'}, {'news_id': 'N49374', 'title': "Princess Beatrice's fashion hits and misses over the years"}, {'news_id': 'N14176', 'title': 'Blueberry Dump Cake Satisfies Every Sweet Tooth'}, {'news_id': 'N60584', 'title': "Those Grueling Workouts May Not Help You Lose Belly Fat, but Here's What Will"}, {'news_id': 'N10', 'title': '7 Running Workouts for Weight Loss'}, {'news_id': 'N46830', 'title': "'This is not normal': Sen. Manchin reacts to Vindman attacks"}, {'news_id': 'N41147', 'title': 'This Sony PS5 feature could end the PlayStation vs Xbox battle once and for all'}, {'news_id': 'N61914', 'title': '50 Great Jobs for Retirees'}, {'news_id': 'N21253', 'title': '5 Incredible, Research-Backed Benefits of Having a Passion Outside Work'}, {'news_id': 'N24905', 'title': 'Grieder: Special election in House District 28 portends a deeply polarized 2020 election cycle'}, {'news_id': 'N65207', 'title': 'Tennessee has deadliest year yet for drug overdoses, as nearby states improve'}, {'news_id': 'N16430', 'title': 'This Rare Albino Hedgehog Was Rescued In California'}, {'news_id': 'N35616', 'title': 'Why more employers are helping workers pay off student loans'}, {'news_id': 'N23386', 'title': "I'm an American who moved to Canada  here's why I'll never move back"}, {'news_id': 'N43484', 'title': 'The Top 25 Holiday Gifts For Women That Will Be Flying Off the Shelves in 2019'}, {'news_id': 'N59794', 'title': '40 Things (Probably) Only Baby Boomers Will Remember'}, {'news_id': 'N15483', 'title': "It's National Check Your Meds Day"}, {'news_id': 'N62736', 'title': 'The 20 best horror games of all time'}, {'news_id': 'N35080', 'title': '5 Excellent Dividend Stocks to Buy for the Holiday Season'}, {'news_id': 'N19146', 'title': 'The most (and least) tax-friendly states for retirees'}, {'news_id': 'N17041', 'title': "The Eagles Soar and Perform 'Hotel California' For the First Time in Its Entirety in Las Vegas"}, {'news_id': 'N48072', 'title': 'Sacramento police look for driver in deadly hit-and-run'}, {'news_id': 'N18287', 'title': "From McDonald's Szechuan Sauce to the Popeyes' sandwich: 6 out-of-control fast-food menu launches that shook America to its core"}, {'news_id': 'N41146', 'title': 'GM Spring Hill could ramp up output soon as union leaders laud stand in national strike'}, {'news_id': 'N31161', 'title': 'Astros have a lot of baseball left despite two bad losses to Nationals'}, {'news_id': 'N37461', 'title': "Queen Elizabeth Once Trolled a Group of Tourists Who Didn't Recognize Her at Balmoral Castle"}, {'news_id': 'N39490', 'title': "Lenape protest groundbreaking of Passaic's new Dundee Island Park, say it's 'sacred ground'"}, {'news_id': 'N8691', 'title': 'The Bugatti Chiron Super Sport 300+ Briefly Went Airborne During Its Record Run'}, {'news_id': 'N26444', 'title': 'Cincinnati vs UConn Football History'}, {'news_id': 'N30868', 'title': 'How to Spot Common Sneaky Foods That Contain Gluten'}, {'news_id': 'N56406', 'title': 'Bicyclist struck by train in Beverly; Delays on Newburyport/Rockport line'}, {'news_id': 'N56618', 'title': "CNN and MSNBC hit Ingraham guest for accusing White House official testifying in impeachment inquiry of 'espionage'"}, {'news_id': 'N5373', 'title': "If These Spooky Quotes Don't Get You in the Halloween Mood, Nothing Will"}, {'news_id': 'N36464', 'title': 'Portion of I-90 reopened after two killed in head-on collision during OSP chase in Euclid'}, {'news_id': 'N38308', 'title': "45 Sneaky Signs You're Unhealthier Than You May Think"}, {'news_id': 'N12440', 'title': 'Trailer - One Last Night'}, {'news_id': 'N2540', 'title': 'Pakistan PM reveals what he told Prince William at lunch'}, {'news_id': 'N42716', 'title': "Trolls Told Me I'm Too Ugly To Post Pics. Then I Did And Something Incredible Happened."}, {'news_id': 'N39638', 'title': 'Want to retire and live in an RV full time? 8 things you need to know'}, {'news_id': 'N24900', 'title': 'Bare Knuckle Knockout! Watch Gabriel Gonzaga Whup Bigfoot Silva In Tampa'}, {'news_id': 'N9947', 'title': '10 Job Skills Worth Six-Figure Salaries'}, {'news_id': 'N25567', 'title': 'The Fast and the Furious Director Rob Cohen Accused of Sexual Assault'}, {'news_id': 'N25205', 'title': '14 hilarious photos that prove Kate Middleton is just like us'}, {'news_id': 'N61681', 'title': '18 Electric Wiring Fails That Will Make You Wince'}, {'news_id': 'N59709', 'title': "Adrian Peterson had to 'hold back tears' in return to Minnesota"}, {'news_id': 'N57930', 'title': 'I Quit My Glamorous Corporate Job to Travel the World'}, {'news_id': 'N9013', 'title': 'Southwest flight attendant alleges pilots live streamed video from camera in lavatory'}, {'news_id': 'N15651', 'title': "The penthouse of NYC's Woolworth Building just got a $31 million price cut. Check out 'The Pinnacle,' which occupies the top 5 floors of the iconic, green-roofed skyscraper."}, {'news_id': 'N63682', 'title': '12 Life-Changing Career Tips From Navy SEALs'}, {'news_id': 'N51784', 'title': 'Martin Truex Jr. through the years'}, {'news_id': 'N41869', 'title': "5 Turkey Cooking Tips That'll Guarantee You Have the Perfect Bird"}, {'news_id': 'N13882', 'title': "Adrian Peterson had to 'hold back tears' in return to Minnesota"}, {'news_id': 'N6258', 'title': 'These Room Divider Ideas Will Transform Your Home in an Instant'}, {'news_id': 'N27641', 'title': "Buttigieg: 'Not going to get in the middle' of Hillary Clinton attacks on Tulsi Gabbard"}, {'news_id': 'N50246', 'title': 'I quit my job, m

Semantic vector

In [142]:
sentence_vector= SentenceVector(models.sentence_model)

model_context.semantic_vector_list = sentence_vector.get_vector(model_context.title_list)
# print(model_context.semantic_vector_list)
sentence_vector.overview()

metric, example = sentence_vector.summary()

print("\nSummary of Sentence Embedding:")
display(metric)
print("\nExample of Sentence Embedding:")
display(example)

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

============================================================
Sentence Embedding Overview
[Sentence is: N55528]
============================================================
Documents : 300
Dimension : 384
Shape     : (384,)

First vector (first 10 values):
[-0.0093  0.0424  0.059   0.0121  0.0334  0.0196  0.0274 -0.0615 -0.0362 -0.039 ] ...

Summary of Sentence Embedding:

                Metric                Value
0      Embedding Model  SentenceTransformer
1  Number of Documents                  300
2  Embedding Dimension                  384
3         Output Shape               (384,)

Example of Sentence Embedding:

,News ID,Sample Title,Embedding (first 10 dims)
0,N55528,"The Brands Queen Elizabeth, Prince Charles, an...","[-0.0093, 0.0424, 0.0590, 0.0121, 0.0334, 0.01..."

In [143]:
bertopic_vector = BERTopicVector(models.topic_model)

topics_vector = bertopic_vector.get_vector(model_context.title_list, model_context.semantic_vector_list)
model_context.topics_vector_list = topics_vector
bertopic_vector.overview()

metric, topic, example = bertopic_vector.summary()
print("\nSummary of BERTopic:")
display(metric)
print("\nTopic Information:")
display(topic)
print("\nExample of BERTopic:")
display(example)

2026-07-17 22:14:08,819 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-07-17 22:14:08,993 - BERTopic - Dimensionality - Completed ✓
2026-07-17 22:14:08,995 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-07-17 22:14:09,016 - BERTopic - Cluster - Completed ✓
2026-07-17 22:14:09,019 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-07-17 22:14:09,037 - BERTopic - Representation - Completed ✓

============================================================
BERTopic Overview
============================================================
Number of documents : 300
Number of topics    : 6

Topic distribution:
   Topic  Count
0     -1     36
1      0    116
2      1     41
3      2     39
4      3     29
5      4     23
6      5     16

First 5 documents:
N55528
Title : The Brands Queen Elizabeth, Prince Charles, and Prince Philip Swear By
Topic : 1
----------------------------------------
N19639
Title : 50 Worst Habits For Belly Fat
Topic : 0
----------------------------------------
N61837
Title : The Cost of Trump's Aid Freeze in the Trenches of Ukraine's War
Topic : 5
----------------------------------------
N53526
Title : I Was An NBA Wife. Here's How It Affected My Mental Health.
Topic : 0
----------------------------------------
N38324
Title : How to Get Rid of Skin Tags, According to a Dermatologist
Topic : 0
----------------------------------------

Probability shape:
(6,)

First 5 probability vectors:
N55528 -> [0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000, ...]
N19639 -> [1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, ...]
N61837 -> [0.0517, 0.0731, 0.0443, 0.0713, 0.0999, 0.4584, ...]
N53526 -> [0.2926, 0.1637, 0.0664, 0.1782, 0.1622, 0.1368, ...]
N38324 -> [0.3970, 0.1090, 0.0515, 0.1483, 0.1303, 0.0968, ...]

Summary of BERTopic:

                Metric     Value
0          Topic Model  BERTopic
1  Number of Documents       300
2     Number of Topics         6
3   Number of Outliers        36
4    Probability Shape      (6,)

Topic Information:

   Topic  Count                            Top Keywords
0     -1     36                                 Outlier
1      0    116         things, make, 2019, 50, recipes
2      1     41        royal, kate, queen, prince, star
3      2     39   nfl, football, week, season, patriots
4      3     29            tv, vegas, ford, chevy, 2021
5      4     23   police, killed, man, causes, maryland
6      5     16  2020, house, clinton, trumps, election

Example of BERTopic:

,News ID,Sample Title,Assigned Topic,Probability Distribution
0,N55528,"The Brands Queen Elizabeth, Prince Charles, an...",1,"[0.0000, 1.0000, 0.0000, 0.0000, 0.0000, 0.0000]"

Represented vector

In [171]:
class RepresentedVector(Vector):
    def __init__(self, title_list, sentence_dict, bertopic_dict):
        self.title_list = title_list
        self.sentence_dict = sentence_dict
        self.bertopic_dict = bertopic_dict
        self.represented_vector = {}
      
    def get_vector(self):
        self.represented_vector = {
            news["news_id"]: {
                "title": news["title"],
                "semantic": self.sentence_dict[news["news_id"]],
                "topic": self.bertopic_dict[news["news_id"]]["topic"],
                "topic_distribution": self.bertopic_dict[news["news_id"]]["probability"]
            }
            for news in self.title_list
        }

        return self.represented_vector

    def overview(self):
        print("=" * 80)
        print("Represented Vector Overview")
        print("=" * 80)

        print(f"Documents           : {len(self.represented_vector)}")

        first_news_id = next(iter(self.represented_vector))

        sample = self.represented_vector[first_news_id]

        print(f"Semantic Dimension  : {len(sample['semantic'])}")
        print(f"Topic Distribution  : {len(sample['topic_distribution'])}")
        print(f"Stored Fields       : {list(sample.keys())}")

        print("=" * 80)
        
    def preview_vector(vector, preview_dims=4):
        vector = [round(float(x), 4) for x in vector]

        if len(vector) <= preview_dims * 2:
            return vector

        return (
            vector[:preview_dims]
            + ["..."]
            + vector[-preview_dims:]
        )

    def summary(self, sample_index=0, preview_dims=4):

        news = self.title_list[sample_index]
        news_id = news["news_id"]

        represented = self.represented_vector[news_id]

        semantic = represented["semantic"]
        probability = represented["topic_distribution"]

        def preview(vector):
            vector = [round(float(x), 4) for x in vector]

            if len(vector) <= preview_dims * 2:
                return vector

            return (
                vector[:preview_dims]
                + ["..."]
                + vector[-preview_dims:]
            )

        semantic_preview = preview(semantic)
        probability_preview = preview(probability)

        summary_df = pd.DataFrame({
            "Field": [
                "News ID",
                "Title",
                "Assigned Topic",
                "Semantic Dimension",
                "Topic Distribution Dimension"
            ],
            "Value": [
                news_id,
                represented["title"],
                represented["topic"],
                len(semantic),
                len(probability)
            ]
        })

        represented_preview = {
            news_id: {
                "title": represented["title"],
                "semantic": semantic_preview,
                "topic": represented["topic"],
                "topic_distribution": probability_preview
            }
        }

        return summary_df, represented_preview

In [172]:
represented_vector = RepresentedVector(model_context.title_list, model_context.semantic_vector_list, model_context.topics_vector_list)

# print(model_context.semantic_vector_list)
# print(model_context.semantic_vector_list)
# print(model_context.topics_vector_list)

represented_vector.get_vector()
represented_vector.overview()
represented_vector.summary(sample_index=0, preview_dims=4)

================================================================================
Represented Vector Overview
================================================================================
Documents           : 300
Semantic Dimension  : 384
Topic Distribution  : 6
Stored Fields       : ['title', 'semantic', 'topic', 'topic_distribution']
================================================================================

(                          Field  \
 0                       News ID
 1                         Title
 2                Assigned Topic
 3            Semantic Dimension
 4  Topic Distribution Dimension

                                                Value
 0                                             N55528
 1  The Brands Queen Elizabeth, Prince Charles, an...
 2                                                  1
 3                                                384
 4                                                  6  ,
 {'N55528': {'title': 'The Brands Queen Elizabeth, Prince Charles, and Prince Philip Swear By',
   'semantic': [-0.0093,
    0.0424,
    0.059,
    0.0121,
    '...',
    0.0517,
    -0.1316,
    0.0508,
    -0.0301],
   'topic': 1,
   'topic_distribution': [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]}})

#   User Representation Vector

##  Prepare sample data User Representation

In [ ]:
behaviours_path = os.path.join(destination, "behaviors.tsv")

news = pd.read_csv(
    news_path,
    sep="\t",
    names=[
        "news_id",
        "category",
        "subcategory",
        "title",
        "abstract",
        "url",
        "title_entities",
        "abstract_entities"
    ]
)

news_dict = news.set_index("news_id")["title"].to_dict()

columns_behaviours = [
    "user_id",
    "time",
    "history",
    "impressions"
]

behaviours = pd.read_csv(
    behaviours_path,
    sep="\t",
    names=columns_behaviours,
    
)

behaviours = behaviours[["user_id", "history"]]
behaviours = behaviours.dropna(subset=["history"])

behaviours["titles"] = behaviours["history"].apply(
    lambda history: [
        news_dict[news_id]
        for news_id in history.split()
        if news_id in news_dict
    ]
)

sample = behaviours.sample(
    n=10,
    random_state=42
).reset_index(drop=True)

sample_dir = r"D:\CDNC\MIND-research\data\sample"

sample.to_csv(
    os.path.join(sample_dir, "behaviours.csv"),
    index=False
)

print(sample.head())
print("Sample shape: ", sample.shape)

## Get Represented Vector of 1 user

In [40]:
repres = represented_vector.get_vector()
print(len(repres))

300