#   Data analysis

##  Import library

In [1]:
import os
import kagglehub
import shutil
import pandas as pd

##  Init data

In [2]:
class Dataset:
    def __init__(self):
        self.destination = r"D:\CDNC\MIND-research\data\raw"
        
        self.news_path = os.path.join(self.destination, "news.tsv")
        self.news_columns = [
            "News_ID",
            "Category",
            "SubCategory",
            "Title",
            "Abstract",
            "URL",
            "Title_Entities",
            "Abstract_Entities",
        ]
        
        self.behaviours_path = os.path.join(self.destination, "behaviors.tsv")
        self.behaviours_columns = [
            "user_id",
            "time",
            "history",
            "impressions"
        ]
        
    def getNewsData(self):
        self.newsData = pd.read_csv(
            self.news_path,
            sep="\t",
            names = self.news_columns
        )
        
        print("Got news dataset !! \n")
        display(self.newsData.head())
        self.newsData.head().to_html("news_sample.html")
        return self.newsData
    
    def anaNewsData(self):
        if not hasattr(self, "newsData"):
            self.getNewsData()

        stats = {
            "Number of news articles": len(self.newsData),
            "Number of categories": self.newsData["Category"].nunique(),
            "Number of subcategories": self.newsData["SubCategory"].nunique(),
            "Number of missing values": self.newsData.isnull().sum().sum(),
            "Number of duplicate News_ID": self.newsData["News_ID"].duplicated().sum(),
        }

        stats_df = pd.DataFrame(
            stats.items(),
            columns=["Statistic", "Value"]
        )

        print("News Dataset Statistics\n")
        display(stats_df)

        stats_df.to_html("news_statistics.html", index=False)

        return stats_df
        
    
    def getBehavioursData(self):
        self.behavioursData = pd.read_csv(
            self.behaviours_path,
            sep="\t",
            names=self.behaviours_columns
        )
        
        print("Got behaviours dataset !! \n")
        display(self.behavioursData.head())
        self.behavioursData.head().to_html("behaviours_sample.html")
        return self.behavioursData
    
    def anaBehavioursData(self):
        if not hasattr(self, "behavioursData"):
            self.getBehavioursData()

        stats = {
            "Number of behaviour records": len(self.behavioursData),
            "Number of unique users": self.behavioursData["user_id"].nunique(),
            "Number of missing values": self.behavioursData.isnull().sum().sum(),
            "Number of duplicate records": self.behavioursData.duplicated().sum(),
        }

        stats_df = pd.DataFrame(
            stats.items(),
            columns=["Statistic", "Value"]
        )

        print("Behaviours Dataset Statistics\n")
        display(stats_df)

        stats_df.to_html("behaviours_statistics.html", index=False)

        return stats_df

In [3]:
ds = Dataset()
news_ds = ds.getNewsData()
print("------------------------")

ds.anaNewsData()

Got news dataset !!

,News_ID,Category,SubCategory,Title,Abstract,URL,Title_Entities,Abstract_Entities
0,N55528,lifestyle,lifestyleroyals,"The Brands Queen Elizabeth, Prince Charles, an...","Shop the notebooks, jackets, and more that the...",https://assets.msn.com/labs/mind/AAGH0ET.html,"[{""Label"": ""Prince Philip, Duke of Edinburgh"",...",[]
1,N19639,health,weightloss,50 Worst Habits For Belly Fat,These seemingly harmless habits are holding yo...,https://assets.msn.com/labs/mind/AAB19MK.html,"[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik...","[{""Label"": ""Adipose tissue"", ""Type"": ""C"", ""Wik..."
2,N61837,news,newsworld,The Cost of Trump's Aid Freeze in the Trenches...,Lt. Ivan Molchanets peeked over a parapet of s...,https://assets.msn.com/labs/mind/AAJgNsz.html,[],"[{""Label"": ""Ukraine"", ""Type"": ""G"", ""WikidataId..."
3,N53526,health,voices,I Was An NBA Wife. Here's How It Affected My M...,"I felt like I was a fraud, and being an NBA wi...",https://assets.msn.com/labs/mind/AACk2N6.html,[],"[{""Label"": ""National Basketball Association"", ..."
4,N38324,health,medical,"How to Get Rid of Skin Tags, According to a De...","They seem harmless, but there's a very good re...",https://assets.msn.com/labs/mind/AAAKEkt.html,"[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI...","[{""Label"": ""Skin tag"", ""Type"": ""C"", ""WikidataI..."

------------------------
News Dataset Statistics

                     Statistic  Value
0      Number of news articles  51282
1         Number of categories     17
2      Number of subcategories    264
3     Number of missing values   2673
4  Number of duplicate News_ID      0

                     Statistic  Value
0      Number of news articles  51282
1         Number of categories     17
2      Number of subcategories    264
3     Number of missing values   2673
4  Number of duplicate News_ID      0

In [4]:
behaviours_ds = ds.getBehavioursData()

ds.anaBehavioursData()

Got behaviours dataset !!

,user_id,time,history,impressions
1,U13740,11/11/2019 9:05:58 AM,N55189 N42782 N34694 N45794 N18445 N63302 N104...,N55689-1 N35729-0
2,U91836,11/12/2019 6:11:30 PM,N31739 N6072 N63045 N23979 N35656 N43353 N8129...,N20678-0 N39317-0 N58114-0 N20495-0 N42977-0 N...
3,U73700,11/14/2019 7:01:48 AM,N10732 N25792 N7563 N21087 N41087 N5445 N60384...,N50014-0 N23877-0 N35389-0 N49712-0 N16844-0 N...
4,U34670,11/11/2019 5:28:05 AM,N45729 N2203 N871 N53880 N41375 N43142 N33013 ...,N35729-0 N33632-0 N49685-1 N27581-0
5,U8125,11/12/2019 4:11:21 PM,N10078 N56514 N14904 N33740,N39985-0 N36050-0 N16096-0 N8400-1 N22407-0 N6...

Behaviours Dataset Statistics

                     Statistic   Value
0  Number of behaviour records  156965
1       Number of unique users   50000
2     Number of missing values    3238
3  Number of duplicate records       0

                     Statistic   Value
0  Number of behaviour records  156965
1       Number of unique users   50000
2     Number of missing values    3238
3  Number of duplicate records       0